version: "3"
services:
  localstack:
    image: localstack/localstack:1.2.0
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
    environment:
      - SERVICES=sqs,sns,es,elasticsearch
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD/src/test/resources/localstack:/docker-entrypoint-initaws.d

  pos-db:
    image: postgres:14
    networks:
      - hmpps
    container_name: pos-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pos
      - POSTGRES_USER=pos
      - POSTGRES_DB=pos

networks:
  hmpps:
