---
# Values here are the same across all environments
cron:
  SYNTHETIC_MONITOR_CRON_EXPRESSION: "*/10 * * * *"
  # default is to suspend the restore - only want it happening on preprod
  suspendRestore: true

alertManagerReceiver: digital-prison-service-dev

generic-service:
  nameOverride: prisoner-offender-search

  image:
    repository: quay.io/hmpps/prisoner-offender-search
    tag: app_version    # override at deployment time
    port: 8080

  replicaCount: 4

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /prisoner-index/queue-housekeeping {
          deny all;
          return 401;
        }
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        location /synthetic-monitor {
          deny all;
          return 401;
        }
    tlsSecretName: prisoner-offender-search-cert

  resources:
    limits:
      memory: 2Gi
      cpu: 2000m
    requests:
      memory: 856Mi
      cpu: 128m

  startupProbe:
    httpGet:
      path: /health/liveness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 30

  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3

  serviceAccountName: prisoner-offender-search

  env:
    SERVER_PORT: "8080"
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: "logstash"
    INDEX_COMPLETE_THRESHOLD: 700000
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    INDEX_INCENTIVES: true
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    prisoner-offender-search:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "PRISONER_OFFENDER_SEARCH_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "PRISONER_OFFENDER_SEARCH_SECRET"
      RESTRICTED_PATIENTS_CLIENT_ID: "RESTRICTED_PATIENTS_CLIENT_ID"
      RESTRICTED_PATIENTS_CLIENT_SECRET: "RESTRICTED_PATIENTS_CLIENT_SECRET"
      INCENTIVES_CLIENT_ID: "INCENTIVES_CLIENT_ID"
      INCENTIVES_CLIENT_SECRET: "INCENTIVES_CLIENT_SECRET"
    pos-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENTQUEUE_QUEUE_NAME: "sqs_pos_name"
    pos-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_EVENTQUEUE_DLQ_NAME: "sqs_pos_name"
    pos-idx-sqs-instance-output:
      HMPPS_SQS_QUEUES_INDEXQUEUE_QUEUE_NAME: "sqs_pos_name"
    pos-idx-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_INDEXQUEUE_DLQ_NAME: "sqs_pos_name"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    sqs-domain-event-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-event-dlq-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_DLQ_NAME: "sqs_queue_name"
    elasticsearch:
      ELASTICSEARCH_PROXY_URL: "aws_es_proxy_url"
    pos-rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    analyticplatform-1: "34.250.17.221/32"
    analyticplatform-2: "34.251.212.33/32"
    analyticplatform-3: "34.252.4.39/32"
    hmp-fosseway-1: "35.177.153.88/32"
    hmp-fosseway-2: "52.56.95.43/32"
    hmp-fosseway-3: "52.56.57.70/32"
    hmp-fosseway-4: "18.135.112.100/32"
    hmp-fosseway-5: "18.135.112.128/32"
    hmp-fosseway-6: "18.135.112.181/32"

generic-prometheus-alerts:
  targetApplication: prisoner-offender-search
