info.app:
  name: HMPPS Prisoner Offender Search
  version: 1.0

spring:
  application:
    name: prisoner-offender-search

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

  codec:
    max-in-memory-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${api.base.url.oauth}/.well-known/jwks.json

      client:
        registration:
          nomis-api:
            provider: hmpps-auth
            client-id: ${oauth.client.id}
            client-secret: ${oauth.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        restricted-patients-api:
          provider: hmpps-auth
          client-id: ${restricted-patients.client.id}
          client-secret: ${restricted-patients.client.secret}
          authorization-grant-type: client_credentials
          scope: read
        provider:
          hmpps-auth:
            token-uri: ${api.base.url.oauth}/oauth/token

  profiles:
    groups:
      dev:
        - "stdout"
      test:
        - "stdout"

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

aws:
  region: eu-west-2
  provider: aws

hmpps.sqs:
  queueAdminRole: ROLE_PRISONER_INDEX
  queues:
    indexqueue:
      asyncQueueClient: true
      asyncDlqClient: true

elasticsearch:
  proxy:
    url: http://aws-es-proxy-service:9200

search:
  keyword:
    timeout-seconds: 10
    max-results: 200
  detailed:
    timeout-seconds: 10
    max-results: 100

index:
  page-size: 1000
  complete-threshold: 700000

