server:
  shutdown: immediate

aws:
  provider: localstack

sqs:
  endpoint:
    url: http://localhost:4576

elasticsearch:
  proxy:
    url: http://localhost:4571

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      nomis: http://localhost:8093

oauth:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
