sqs:
  endpoint.url: http://localhost:4576
  provider: localstack

es:
  endpoint.url: http://localhost:4578
  provider: localstack

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      nomis: http://localhost:8093

graceful:
  shutdown.enabled: false

elasticsearch:
  port: 4571
  scheme: http
  host: localhost
