server:
  shutdown: immediate

spring:
  profiles:
    include: stdout

aws:
  provider: localstack

sqs:
  endpoint.url: http://localhost:4576

elasticsearch:
  port: 4571
  scheme: http
  host: localhost

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      nomis: http://localhost:8093

oauth:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret
