server:
  shutdown: immediate

aws:
  provider: localstack

elasticsearch:
  proxy:
    url: http://es01.eu-west-2.es.localhost.localstack.cloud:4566

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      nomis: http://localhost:8093
      restricted-patients: http://localhost:8095
      incentives: http://localhost:8096

oauth:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret

restricted-patients:
  client:
    id: prisoner-search-to-restricted-patients-api
    secret: clientsecret

incentives:
  client:
    id: incentives-api
    secret: clientsecret

index:
  page-size: 1000
  complete-threshold: 50

hmpps.sqs:
  provider: localstack
  queues:
    eventqueue:
      queueName: event-queue
      dlqName: event-dlq
    hmppsdomainqueue:
      queueName: hmpps-domain-queue
      dlqName: hmpps-domain-dlq
    indexqueue:
      queueName: index-queue
      dlqName: index-dlq
  topics:
    eventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:event-topic
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-event-topic
