server:
  shutdown: immediate

aws:
  provider: localstack

elasticsearch:
  proxy:
    url: http://localhost:4571

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      nomis: http://localhost:8093
      restricted-patients: http://localhost:8095

oauth:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret

restricted-patients:
  client:
    id: prisoner-search-to-restricted-patients-api
    secret: clientsecret

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

index:
  page-size: 1000
  complete-threshold: 50

hmpps.sqs:
  provider: localstack
  queues:
    eventqueue:
      queueName: event-queue
      dlqName: event-dlq
    indexqueue:
      queueName: index-queue
      dlqName: index-dlq

hmpps.sns:
  topics:
    eventTopic:
      topicArn: arn:aws:sns:eu-west-2:000000000000:event-topic
