apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-full-index-comparison
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "05 19 * * 1,3,5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: remove-differences
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XGET http://prisoner-offender-search/prisoner-index/automated-reconcile
          restartPolicy: Never
