apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-index-housekeeping
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: housekeeping
              image: quay.io/hmpps/dps-tools
              args:
                - /bin/sh
                - -c
                - curl -XPUT http://prisoner-offender-search/prisoner-index/queue-housekeeping
          restartPolicy: Never
