apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-remove-old-differences
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "45 22 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: remove-differences
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XDELETE http://prisoner-offender-search/prisoner-differences/delete
          restartPolicy: Never
