apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  PRISON_TO_NHS_CLIENT_ID: {{ .Values.secrets.PRISON_TO_NHS_CLIENT_ID | b64enc | quote }}
  PRISON_TO_NHS_CLIENT_SECRET: {{ .Values.secrets.PRISON_TO_NHS_CLIENT_SECRET | b64enc | quote }}
