apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-synthetic-monitor
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.SYNTHETIC_MONITOR_CRON_EXPRESSION }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: synthetic-monitor
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 http://prisoner-offender-search/synthetic-monitor
          restartPolicy: Never
