---
# Environment specific values, override helm_deploy/prisoner-offender-search/values.yaml
generic-service:
  replicaCount: 4
  ingress:
    host: "prisoner-offender-search.prison.service.justice.gov.uk"
  env:
    API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_NOMIS: "https://api.prison.service.justice.gov.uk"
    API_BASE_URL_RESTRICTED_PATIENTS: "https://restricted-patients-api.hmpps.service.justice.gov.uk"
    DIFF_HOST: "https://prisoner-offender-search.prison.service.justice.gov.uk"
    INDEX_COMPLETE_THRESHOLD: 500000
    DIFF_TELEMETRY: true
    DIFF_EVENTS: true

  # Additional allowlist rules
  # See also allowlist values helm_deploy/prisoner-offender-search/values.yaml
  allowlist:
    prum-prod-platform-1: "18.170.20.75/32"
    prum-prod-platform-2: "35.177.223.199/32"
    prum-prod-platform-3: "18.170.155.82/32"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: syscon
  rdsAlertsDatabases:
    cloud-platform-64baa94287c3aeff: "prisoner search"
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-prod-prisoner_offender_search_queue"
    - "Digital-Prison-Services-prod-prisoner_offender_search_queue_dl"
    - "dps-prod-prisoner_offender_index_queue"
    - "dps-prod-prisoner_offender_index_queue_dl"
  sqsAlertsOldestThreshold: 30 #default
  sqsAlertsTotalMessagesThreshold: 100 #default
