---
# Environment specific values, override helm_deploy/prisoner-offender-search/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "prisoner-offender-search.prison.service.justice.gov.uk"
  env:
    API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_NOMIS: "https://api.prison.service.justice.gov.uk"
    INDEX_COMPLETE_THRESHOLD: 500000

# Sets where alerts will be delivered, via Alertmanager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
