---
# Environment specific values, override helm_deploy/prisoner-offender-search/values.yaml
generic-service:
  replicaCount: 4
  ingress:
    host: "prisoner-offender-search-preprod.prison.service.justice.gov.uk"
  env:
    API_BASE_URL_OAUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_NOMIS: "https://api-preprod.prison.service.justice.gov.uk"
    INDEX_COMPLETE_THRESHOLD: 500000

  # Additional allowlist rules
  # See also allowlist values helm_deploy/prisoner-offender-search/values.yaml
  allowlist:
    prum-test-platform-1: "18.134.149.68/32"
    prum-test-platform-2: "18.133.201.123/32"
    prum-test-platform-3: "52.56.76.34/32"

# Sets where alerts will be delivered, via Alertmanager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
