# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/prisoner-offender-search
  tag: latest
  port: 8080

ingress:
  enabled: true
  enable_allowlist: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: prisoner-offender-search.prison.service.justice.gov.uk
      cert_secret: prisoner-offender-search-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  API_BASE_URL_NOMIS: "https://api.prison.service.justice.gov.uk"
  INDEX_COMPLETE_THRESHOLD: 700000

cron:
  SYNTHETIC_MONITOR_CRON_EXPRESSION: "1 * * * *"

allowlist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  analyticplatform-1: "34.250.17.221/32"
  analyticplatform-2: "34.251.212.33/32"
  analyticplatform-3: "34.252.4.39/32"
